export const ITEM_BALANCE = {
  hitImmunitySeconds: 1,
  rocketTargetProtectionSeconds: 2,
  bubblePopImmunitySeconds: 0.5,
  minimumSpeedMultiplier: 0.1,
  maximumSpeedMultiplier: 1.35,
  nitro: {
    armProgress: 0.35,
    fallbackProgress: 0.68,
    triggerRank: 4,
    gapThreshold: 0.045,
    speedMultiplier: 1.15,
    durationSeconds: 1.3,
  },
  draftFin: {
    armProgress: 0.25,
    maxGap: 0.028,
    lateralRadius: 0.14,
    holdSeconds: 0.75,
    speedMultiplier: 1.08,
    durationSeconds: 1.0,
  },
  paddleBurst: {
    armProgress: 0.65,
    speedMultiplier: 1.07,
    durationSeconds: 1.2,
  },
  rocket: {
    armProgress: 0.25,
    disableProgress: 0.96,
    maximumTargetDistance: 0.22,
    endGameTargetDistanceMultiplier: 1.5,
    projectileSpeed: 0.16,
    lifetimeSeconds: 3,
    hitRadius: 0.014,
    armingTicks: 2,
    slowMultiplier: 0.68,
    slowDurationSeconds: 1.15,
  },
  shockAbsorber: {
    slowMultiplier: 0.88,
    slowDurationSeconds: 0.55,
    hornPushMultiplier: 0.5,
    hornShoveMultiplier: 0.5,
  },
  banana: {
    armProgress: 0.2,
    fallbackProgress: 0.55,
    endGameDropProgress: 0.72,
    closeBehindDistance: 0.085,
    lifetimeSeconds: 8,
    dropBehindProgress: 0.012,
    armingSeconds: 0.2,
    hitProgressRadius: 0.013,
    hitLateralRadius: 0.18,
    minimumTrapSpacing: 0.015,
    progressKnockback: 0.035,
    lateralSlip: 0.42,
  },
  horn: {
    armProgress: 0.22,
    progressRadius: 0.024,
    lateralRadius: 0.32,
    lateralPush: 0.88,
    lateralShove: 0.2,
    fallbackProgress: 0.76,
  },
  bubbleShield: {
    durationSeconds: 4.5,
    endGameBurnProgress: 0.82,
  },
  autoUse: {
    endGameBurnProgress: 0.78,
    forceBurnProgress: 0.92,
  },
} as const
