export const ITEM_BALANCE = {
  hitImmunitySeconds: 1,
  rocketTargetProtectionSeconds: 2,
  bubblePopImmunitySeconds: 0.5,
  minimumSpeedMultiplier: 0.05,
  maximumSpeedMultiplier: 1.60,
  maxContinuousBoostSeconds: 2.6,
  nitro: {
    armProgress: 0.28,
    fallbackProgress: 0.68,
    triggerRank: 4,
    gapThreshold: 0.045,
    speedMultiplier: 1.25,
    durationSeconds: 1.70,
    ignitionSeconds: 0.18,
    overdriveSeconds: 1.27,
    decaySeconds: 0.25,
  },
  draftFin: {
    armProgress: 0.20,
    maxGap: 0.045,
    lateralRadius: 0.20,
    holdSeconds: 0.75,
    speedMultiplier: 1.20,
    durationSeconds: 1.6,
  },
  paddleBurst: {
    armProgress: 0.65,
    speedMultiplier: 1.18,
    durationSeconds: 1.8,
  },
  rocket: {
    armProgress: 0.25,
    disableProgress: 0.98,
    maximumTargetDistance: 0.32,
    endGameTargetDistanceMultiplier: 1.8,
    projectileSpeed: 0.26,
    lifetimeSeconds: 3.5,
    hitRadius: 0.018,
    armingTicks: 2,
    staggerMultiplier: 0.05,
    staggerDurationSeconds: 1.25,
    recoverySlowMultiplier: 0.35,
    recoveryDurationSeconds: 0.85,
    slowMultiplier: 0.05,
    slowDurationSeconds: 2.10,
  },
  shockAbsorber: {
    staggerMultiplier: 0.40,
    staggerDurationSeconds: 0.40,
    recoverySlowMultiplier: 0.75,
    recoveryDurationSeconds: 0.45,
    slowMultiplier: 0.40,
    slowDurationSeconds: 0.85,
    hornPushMultiplier: 0.4,
    hornShoveMultiplier: 0.4,
  },
  banana: {
    armProgress: 0.2,
    fallbackProgress: 0.55,
    endGameDropProgress: 0.72,
    closeBehindDistance: 0.085,
    lifetimeSeconds: 10,
    dropBehindProgress: 0.012,
    armingSeconds: 0.2,
    hitProgressRadius: 0.015,
    hitLateralRadius: 0.20,
    minimumTrapSpacing: 0.015,
    lateralSlip: 0.65,
    staggerMultiplier: 0.25,
    staggerDurationSeconds: 0.65,
    recoverySlowMultiplier: 0.65,
    recoveryDurationSeconds: 0.55,
    slowMultiplier: 0.25,
    slowDurationSeconds: 1.20,
  },
  horn: {
    armProgress: 0.22,
    progressRadius: 0.045,
    lateralRadius: 0.48,
    lateralPush: 1.20,
    lateralShove: 0.25,
    fallbackProgress: 0.76,
    silenceDurationSeconds: 2.5,
  },
  bubbleShield: {
    durationSeconds: 4.5,
    endGameBurnProgress: 0.65,
    burstMultiplier: 1.08,
    burstDurationSeconds: 1.2,
  },
  menace: {
    predatorRushMultiplier: 1.25,
    predatorRushDurationSeconds: 2.5,
  },
  fortress: {
    surgeMultiplier: 1.08,
    surgeDurationSeconds: 1.2,
    collisionPushMultiplier: 0.7,
    collisionSpeedLossMultiplier: 0.7,
  },
  autoUse: {
    endGameBurnProgress: 0.78,
    forceBurnProgress: 0.92,
  },
} as const
