export const PICKUP_BALANCE = {
  progressRadius: 0.009,
  lateralRadius: 0.18,
  regularPickupCap: 2,
  goldenBoxProbability: 0.12,
  goldenProgressMinimum: 0.35,
  goldenProgressMaximum: 0.75,
  itemHitImmunitySeconds: 1.25,
  rocketTargetProtectionSeconds: 2,
  positiveSpeedCap: 1.2,
  negativeSpeedCap: 0.75,
  miniNitro: { multiplier: 1.08, durationSeconds: 0.85 },
  tailwind: { multiplier: 1.05, durationSeconds: 1.1, lateralStability: 0.72 },
  miniBubble: { durationSeconds: 7 },
  miniRocket: {
    maximumTargetDistance: 0.145,
    projectileSpeed: 0.115,
    lifetimeSeconds: 2.5,
    hitRadius: 0.008,
    slowMultiplier: 0.92,
    slowDurationSeconds: 0.45,
    autoArmProgress: 0.35,
    autoFallbackProgress: 0.88,
  },
  banana: {
    lifetimeSeconds: 6,
    hitProgressRadius: 0.006,
    hitLateralRadius: 0.14,
    minimumTrapSpacing: 0.015,
    slowMultiplier: 0.95,
    slowDurationSeconds: 0.42,
    lateralSlip: 0.075,
    autoFallbackProgress: 0.75,
    closeBehindDistance: 0.055,
  },
  horn: { progressRadius: 0.011, lateralRadius: 0.22, lateralPush: 0.08 },
  feather: { durationSeconds: 5, autoFallbackProgress: 0.8 },
  magnet: { durationSeconds: 0.9, multiplier: 1.04, maximumTargetDistance: 0.16 },
  hazards: {
    ANCHOR: { slowMultiplier: 0.965, durationSeconds: 0.45, wobble: 0.045 },
    WHIRLPOOL: { slowMultiplier: 0.98, durationSeconds: 0.5, wobble: 0.08 },
    ICE_PATCH: { slowMultiplier: 0.985, durationSeconds: 0.5, wobble: 0.1 },
    STICKY_GOO: { slowMultiplier: 0.97, durationSeconds: 0.42, wobble: 0.025 },
  },
} as const

export const POSITION_CATEGORY_WEIGHTS = {
  front: { DEFENSE: 35, ATTACK: 30, UTILITY: 25, MOBILITY: 10 },
  middle: { ATTACK: 30, DEFENSE: 25, MOBILITY: 25, UTILITY: 20 },
  back: { MOBILITY: 38, DEFENSE: 27, ATTACK: 20, UTILITY: 15 },
} as const
