export const PICKUP_BALANCE = {
  progressRadius: 0.010,
  lateralRadius: 0.20,
  regularPickupCap: 3,
  goldenBoxProbability: 0.18,
  goldenProgressMinimum: 0.35,
  goldenProgressMaximum: 0.75,
  itemHitImmunitySeconds: 0.8,
  rocketTargetProtectionSeconds: 1.5,
  positiveSpeedCap: 1.60,
  negativeSpeedCap: 0.05,
  miniNitro: { multiplier: 1.30, durationSeconds: 2.5 },
  tailwind: { multiplier: 1.20, durationSeconds: 3.0, lateralStability: 0.75 },
  miniBubble: { durationSeconds: 6 },
  autoUse: {
    endGameBurnProgress: 0.78,
    forceBurnProgress: 0.92,
    idealManualDelayProgress: 0.05,
  },
  miniRocket: {
    maximumTargetDistance: 0.22,
    endGameTargetDistanceMultiplier: 1.5,
    forceBurnTargetDistanceMultiplier: 2.2,
    projectileSpeed: 0.20,
    lifetimeSeconds: 2.5,
    hitRadius: 0.015,
    armingTicks: 2,
    staggerMultiplier: 0.25,
    staggerDurationSeconds: 0.45,
    recoverySlowMultiplier: 0.65,
    recoveryDurationSeconds: 0.55,
    slowMultiplier: 0.25,
    slowDurationSeconds: 1.00,
    autoArmProgress: 0.25,
    autoFallbackProgress: 0.70,
  },
  banana: {
    lifetimeSeconds: 8,
    dropBehindProgress: 0.012,
    armingSeconds: 0.2,
    hitProgressRadius: 0.014,
    hitLateralRadius: 0.18,
    minimumTrapSpacing: 0.015,
    progressKnockback: 0.040,
    lateralSlip: 0.35,
    autoFallbackProgress: 0.60,
    endGameDropProgress: 0.70,
    closeBehindDistance: 0.075,
  },
  horn: {
    progressRadius: 0.030,
    lateralRadius: 0.42,
    lateralPush: 0.65,
    lateralShove: 0.18,
    endGameProgressRadiusMultiplier: 1.6,
  },
  feather: { durationSeconds: 5, autoFallbackProgress: 0.70, endGameProgress: 0.75 },
  magnet: { durationSeconds: 1.6, multiplier: 1.18, maximumTargetDistance: 0.24 },
  hazards: {
    ANCHOR: { slowMultiplier: 0.82, durationSeconds: 1.5, wobble: 0.065 },
    WHIRLPOOL: { slowMultiplier: 0.85, durationSeconds: 1.6, wobble: 0.12 },
    ICE_PATCH: { slowMultiplier: 0.88, durationSeconds: 1.6, wobble: 0.15 },
    STICKY_GOO: { slowMultiplier: 0.80, durationSeconds: 1.4, wobble: 0.045 },
  },
} as const

export const POSITION_CATEGORY_WEIGHTS = {
  front: { DEFENSE: 34, ATTACK: 26, UTILITY: 22, MOBILITY: 18 },
  middle: { ATTACK: 34, MOBILITY: 28, DEFENSE: 20, UTILITY: 18 },
  back: { MOBILITY: 44, ATTACK: 30, DEFENSE: 16, UTILITY: 10 },
} as const
