export const CORE_BALANCE = {
  tickRate: 60,
  targetDurationSeconds: 56,
  maximumDurationSeconds: 90,
  speedVariation: 0.03,
  accelerationVariation: 0.03,
  impulseMinSeconds: 0.5,
  impulseMaxSeconds: 1.1,
  speedResponse: 1.65,
  lateralResponse: 2.5,
  maximumLateralVelocity: 0.85,
  collisionProgressRadius: 0.009,
  collisionLateralRadius: 0.18,
  collisionPush: 0.040,
  collisionSpeedLoss: 0.008,
  pacingSegmentCount: 4,
  pacingVariation: 0.18,
} as const
